services:
  kotori_blog:
    container_name: kotori_blog
    image: ghcr.io/gohugoio/hugo:v0.147.0
    working_dir: /hugo
    ports:
      - 1313:1313
    tty: true
    volumes:
      - .:/hugo
    command: server --bind=0.0.0.0 -b http://localhost:1313/KotoriBlog/