version: '3'

services:
  kotori_blog:
    container_name: kotori_blog
    build:
      context: .
      dockerfile: dockerfile
      args:
        - HUGO_VERSION=${HUGO_VERSION}
        - HUGO_NAME=${HUGO_NAME}
        - HUGO_URL=${HUGO_URL}
    ports:
      - 1313:1313
    tty: true
    volumes:
      - .:/hugo